infra_host_definition_root: /opt/infra
infra_host_container_root: "{{ infra_host_definition_root }}/containers"
infra_host_data_root: /srv/infra/data
infra_host_packages: []
infra_host_docker_log_max_size: 10m
infra_host_docker_log_max_files: '3'
infra_host_ignore_lid_switch: true
infra_host_logind_lid_drop_in: /etc/systemd/logind.conf.d/60-homelab-lid.conf
