storage_mounts: []
dotfiles_repo: https://github.com/danny-ngo/dotfiles
dotfiles_branch: main
dotfiles_packages_linux: [fastfetch, git, starship, zsh]
dotfiles_packages_macos: [fastfetch, ghostty, git, starship, zsh]
k3s_version: v1.35.6+k3s1
k3s_fetch_kubeconfig: false
pihole_version: v6.4.3
